version: "3"
services:
  node:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "3000:3000"
    depends_on:
      - mongo

  mongo:
    image: mongo:5
    ports:
      - "27017:27017"

  express:
    build:
      context: ./app
      dockerfile: Dockerfile
    volumes:
      - ./app:/app
    ports:
      - "8080:8080"
    depends_on:
      - mongo
